// Getters
export const PAGE_DATA_GETTER = 'games/PAGE_DATA';
export const DATE_RANGE_GETTER = 'games/DATE_RANGE';
export const DATA_KEYS_GETTER = 'games/DATA_KEYS_GETTER';
export const SITE_CHANGE_GETTER = 'games/SITE_CHANGE_GETTER';
export const RESOURCE_LIST_GETTER = 'games/RESOURCE_LIST_GETTER';
export const RESOURCE_DETAIL_GETTER = 'games/RESOURCE_DETAIL_GETTER';
export const RESOURCE_SHOW_PAGE_GETTER = 'games/RESOURCE_SHOW_PAGE_GETTER';

// Mutations
export const MUTATE_DATA_GAMES = 'games/MUTATE_DATA_GAMES';
export const MUTATE_KEYS_GAMES = 'games/MUTATE_KEYS_GAMES';
export const MUTATE_SITE_CHANGE = 'games/MUTATE_SITE_CHANGE';
export const MUTATE_ADD_RESOURCE = 'games/MUTATE_ADD_RESOURCE';
export const MUTATE_LIST_RESOURCE = 'games/MUTATE_LIST_RESOURCE';
export const MUTATE_SHOW_PAGE_RESOURCE = 'games/MUTATE_SHOW_PAGE_RESOURCE';

// Actions
export const ACTION_GAMES_INIT_KEYS = 'games/ACTION_GAMES_INIT_KEYS';
export const ACTION_GAMES_DATA_CHANGE = 'games/ACTION_GAMES_DATA_CHANGE';

export const ACTION_ADD_RESOURCE = 'games/ACTION_ADD_RESOURCE';
export const ACTION_LIST_RESOURCE = 'games/ACTION_LIST_RESOURCE';