spring:
  jpa:
    show-sql: true
    database: HSQL
    hibernate:
      ddl-auto: update
  data:
    jpa.repositories.enabled: true
    rest:
      detection-strategy: annotated
  cache:
    cache-names: ali213Cache,3dmCache,rarBtCache
    type: caffeine
    caffeine:
      spec: maximumSize=999999,expireAfterAccess=24h
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:file:./data/database
    username: sa
    password: